# -*- coding: utf-8 -*-
"""CNEP1a_2_G1.ipynb
Automatically generated by Colaboratory.
Original file is located at
    https://colab.research.google.com/drive/1NgLopfpfrVfLE0iNOcZSh_nYPORDDoA2
"""

#%%
import ctypes
import multiprocessing
import os
import sys, getopt
import random
import math
from pathlib import Path

# import matplotlib.pyplot as plt

## -> Networkx
import networkx as nx
from networkx.readwrite import edgelist
from networkx.algorithms import approximation as approx
from networkx import Graph as gr
## <- Networkx

import itertools

import numpy as np
import payoff_functions
from payoff_functions import get_payoff_function, list_payoff_functions
from graph_io import read_graph, get_node_weight, get_total_weight, print_graph_summary

## -> MultiProcessing
from multiprocessing import *
## <- MultiProcessing

fitness_count = 0
max_fitness_count = 100000

# Global dictionary to store node weights (for weighted graphs)
node_weights = {}

# Note: get_node_weight and get_total_weight are now imported from graph_io

#USAGE INFORMATION
def print_usage():
    print('USAGE: ',os.path.basename(__file__),' -i <inputfile> -t <iterationCount> -v <vertices_to_remove> -e <edges_to_remove>')
    print('        Options:')
    print('            -i : sets input file name relative to script path. E.g. default: ''testdata/urv_email''')
    print('            -t : greedy iteration count (default: vertices^2)');
    print('            -v : number of vertices to remove (default: 2)');
    print('            -t : number of edges to remove (default: 2)');
    print('            -d : debug level (0 - none, 2 - max)')
    
#CONFIGURATION CLASS
class config:

    def __init__(self, input_file, iterCount, iK1, iK2, iDebug=0):
        global node_weights
        
        # Resolve input path: allow bare name (assumed under inputs/) or a provided path
        input_arg = Path(sys.argv[1])
        candidate_paths = [
            input_arg,
            Path("inputs") / input_arg,
            Path("inputs/Testing") / input_arg,
        ]
        input_path = None
        for candidate in candidate_paths:
            if candidate.exists():
                input_path = candidate
                break
        if input_path is None:
            raise FileNotFoundError(f"Input file not found: {input_arg} (tried: {candidate_paths})")

        self.inputFile = str(input_path)

        # Prepare output path under outputs/reruns/greedy with sanitized name
        output_dir = Path("outputs/reruns/greedy")
        output_dir.mkdir(parents=True, exist_ok=True)
        output = output_dir / f"{sys.argv[2]}_{input_path.name}"

        # Use graph_io module to read graph
        self.G, node_weights_loaded = read_graph(str(input_path), detect_weights=True)
        node_weights = node_weights_loaded  # Always a dict now, with weight 1 for unweighted graphs
        
        # Print weight info for debugging
        print_graph_summary(self.G, node_weights)

        # self.G = nx.read_adjlist(self.inputFile, nodetype = int)

        #USE IF GRAPHICAL INTERFACE IS PRESENT, AND GRAPH IS NOT TOO BIG
        #plt.subplot(131)
        #nx.draw(self.G, with_labels=True) #, pos=nx.planar_layout(G), node_color='r', edge_color='b')

        # INIT VALUES
        # self.K1 = iK1 if (iK1>0) else 2 # vertices to delete
        # self.K2 = iK2 if (iK2>0) else 2 # edges to delete
        
        # Node count to remove (fixed)
        self.K1 = int(len(list(self.G.nodes)) * 0.05)  # number of nodes to remove (5%)
        self.K2 = int(len(list(self.G.edges)) * 0.03)  # number of edges to remove (3%)
        
        # Weight budget constraint for nodes; allows override via GREEDY_WEIGHT_BUDGET env var
        total_node_weight = get_total_weight(node_weights, self.G.nodes())
        weight_budget_fraction = float(os.getenv("GREEDY_WEIGHT_BUDGET", "0.05"))
        weight_budget_fraction = max(0.0, min(weight_budget_fraction, 1.0))
        self.weight_budget_fraction = weight_budget_fraction
        self.K1_weight_budget = int(total_node_weight * self.weight_budget_fraction)  # maximum allowed weight sum
        
        self.K = self.K1 + self.K2  # Total budget (count for both nodes and edges)
        self.INF = self.G.number_of_nodes() ** 2
        
        # Iteration count: use env var if set, otherwise default to (K1 + K2)^2
        iter_env = os.getenv("GREEDY_ITERATION_COUNT", "")
        if iter_env:
            self.IterationCount = int(iter_env)
        else:
            self.IterationCount = (self.K1 + self.K2) ** 2  # Original formula


        self.pool_size = multiprocessing.cpu_count() - 1
        self.NIL = -1  #not defined in NetworkX!!!
        #print extra information
        self.iDebug = iDebug

#PRINT CONFIGURATION
def print_config(mainConfig):
    print('Current configuration:\n----------------------')
    print('Pool size: ', mainConfig.pool_size)
    print('Inputfile: ', mainConfig.inputFile,'\n')

    print('Graph properties:\n-----------------')
    print("G - edgecount: " + str(len(mainConfig.G.edges)))
    print("G - nodecount: " + str(len(mainConfig.G.nodes)),'\n')

    print('Vertices to delete: ', mainConfig.K1)
    print('   Edges to delete: ', mainConfig.K2)
    print('Weight budget for nodes: ', mainConfig.K1_weight_budget)
    print('Weight budget fraction: ', mainConfig.weight_budget_fraction)
    print('        Iterations:',mainConfig.IterationCount,'\n')
    print('         Processes:',mainConfig.pool_size,'\n')

#MULTIPROCESSING SETUP
def pool_init(q, pf_name):
    global que, payoff_function # make queue and payoff_function global in workers
    que = q
    # Look up function by name in worker process
    payoff_function = get_payoff_function(pf_name)

# Global payoff function (will be set during initialization)
payoff_function = None

#FITNESS FUNCTION - cover function that uses the selected payoff function
def fitness(lst): ### Cover function that applies the selected payoff function to components
    global fitness_count, payoff_function
    fitness_count = fitness_count + 1
    # Use the global payoff function if set, otherwise default to pairwise connectivity from module
    if payoff_function is not None:
        return payoff_function(lst)
    else:
        # Use the pairwise_connectivity function from payoff_functions module
        return payoff_functions.pairwise_connectivity(lst)

def h_component(lst): 
    return sum(lst)

#GENERATE RANDOM ELEMENT
def select_random(lst):
    return random.choice(lst)

#GENERATE LIST OF BEST VERTICES AND EDGES
def best_nodes_edges_CNEP1A_Alg2(config, SN, SE, GG, current_node_weight): 
    """
    Find best nodes and edges to remove.
    For nodes: respects both count (K1) and weight budget (K1_weight_budget) constraints.
    
    We want to MAXIMIZE the improvement (delta = orig_fitness - new_fitness).
    For minimization payoffs (pairwise, largest): larger delta means bigger decrease.
    For components (negative values): larger delta means more components created.
    """
    selectedEdges = []
    selectedNodes = []
    max_delta = -config.INF  # Start with very negative value, look for maximum
    P = GG.copy()
    P.remove_nodes_from(SN)
    P.remove_edges_from(SE)
    node_f_orig = fitness(nx.connected_components(P))
    SG2 = nx.edges(config.G)
    SG1 = nx.nodes(config.G)
    if (config.iDebug == 2):
        print("--------------------------------------------\nKezdes")
        print("   node_f_orig = ", node_f_orig)
        print(f"   nodes removed: {len(SN)}/{config.K1}, weight: {current_node_weight}/{config.K1_weight_budget}")
    
    # Check node budget: based on both count and weight
    if len(SN) < config.K1:
        for curr_node in SG1:
            if curr_node not in SN:  # Skip already removed nodes
                node_weight = get_node_weight(node_weights, curr_node)
                # Only consider nodes that won't exceed weight budget
                if current_node_weight + node_weight <= config.K1_weight_budget:
                    R = P.copy()
                    R.remove_nodes_from([curr_node])
                    delta = node_f_orig - fitness(nx.connected_components(R))

                    if delta > max_delta:
                        selectedNodes.clear()
                        selectedNodes.append(curr_node)
                        max_delta = delta
                    elif delta == max_delta:
                        selectedNodes.append(curr_node)

    if len(SE) < config.K2:
         for curr_edge in SG2:
            R = P.copy()
            R.remove_edges_from([curr_edge])
            delta = node_f_orig - fitness(nx.connected_components(R))

            if delta > max_delta:
                selectedEdges.clear()
                selectedEdges.append(curr_edge)
                max_delta = delta
            elif delta == max_delta:
                selectedEdges.append(curr_edge)
    if (config.iDebug == 2):
        print("->N:",selectedNodes)   
        print("->E:",selectedEdges)   
    return [selectedNodes, selectedEdges]

# CNP1a Alg2 G1
def CNEP1a_2_G1(config):
    S = []  # Removed nodes
    E = []  # Removed edges
    current_node_weight = 0  # Track cumulative weight of removed nodes
    
    H = config.G.copy()
    
    # Continue while we haven't reached the count limits
    while len(S) < config.K1 or len(E) < config.K2:
        [A, B] = best_nodes_edges_CNEP1A_Alg2(config, S, E, H, current_node_weight)
        
        if (config.iDebug == 2):
            print("B: ", B)
        
        z1 = z2 = config.NIL
        if len(A) > 0:
            z1 = select_random(A)
            if (config.iDebug == 2):
                print("--> (randN)", z1, f"weight={get_node_weight(node_weights, z1)}")
        if len(B) > 0:
            z2 = select_random(B)
            if (config.iDebug == 2):
                print("--> (randE)", z2)

        # Decide what to remove based on budget availability
        if (z1 != config.NIL):
            if (z2 != config.NIL):
                # Both available: choose based on which budget still has room
                node_weight = get_node_weight(node_weights, z1)
                can_add_node = (len(S) < config.K1 and 
                               current_node_weight + node_weight <= config.K1_weight_budget)
                can_add_edge = len(E) < config.K2
                
                if can_add_node and can_add_edge:
                    if random.randint(0, 1) == 1:
                        S.append(z1)
                        current_node_weight += node_weight
                        H.remove_nodes_from([z1])
                        if (config.iDebug == 2):
                            print(f"--> (del)N, total weight now: {current_node_weight}/{config.K1_weight_budget}")
                    else:
                        E.append(z2)
                        H.remove_edges_from([z2])
                        if (config.iDebug == 2):
                            print("--> (del)E")
                elif can_add_node:
                    S.append(z1)
                    current_node_weight += node_weight
                    H.remove_nodes_from([z1])
                    if (config.iDebug == 2):
                        print(f"--> (del)N, total weight now: {current_node_weight}/{config.K1_weight_budget}")
                elif can_add_edge:
                    E.append(z2)
                    H.remove_edges_from([z2])
                    if (config.iDebug == 2):
                        print("--> (del)E")
                else:
                    break  # Both budgets exhausted
            else:
                # Only node available
                node_weight = get_node_weight(node_weights, z1)
                if len(S) < config.K1 and current_node_weight + node_weight <= config.K1_weight_budget:
                    S.append(z1)
                    current_node_weight += node_weight
                    H.remove_nodes_from([z1])
                    if (config.iDebug == 2):
                        print(f"--> (del)N, total weight now: {current_node_weight}/{config.K1_weight_budget}")
                else:
                    break  # Node budget exceeded
        else:
            # Only edge available
            if len(E) < config.K2:
                E.append(z2)
                H.remove_edges_from([z2])
                if (config.iDebug == 2):
                    print("--> (del)E")
            else:
                break  # Edge budget exceeded
    
    if config.iDebug >= 1:
        print(f"\nFinal: Removed {len(S)} nodes (weight: {current_node_weight}/{config.K1_weight_budget}), {len(E)} edges")
    
    return [H, S, E]
    
def makeCNEPRun(config,method,i):
    # Progress output: show iteration counter
    show_progress = os.getenv("GREEDY_SHOW_PROGRESS", "0") == "1"
    if show_progress:
        # Show [current/total] format
        print(f"[{i+1}/{config.IterationCount}]", end=" ", flush=True)
    elif (config.iDebug > 0):
        print('Run: ',i,'/',config.IterationCount)
    [R, SS, EE] = method(config)
    if (config.iDebug == 2):
        print(SS)
    currVal = fitness(nx.connected_components(R))
    if (config.iDebug == 2):
        print(currVal)
    que.put([currVal,SS,EE])


if __name__ == '__main__':
    # WINDOWS: this must be in the __main__ section
    def run(pool):
        tasks = []
        for i in range(mainConfig.IterationCount):
            tasks.append(pool.apply_async(makeCNEPRun,args=(mainConfig,CNEP1a_2_G1,i,)))
        for t in tasks:
            t.get()
    
    ### PROCESSING COMMAND LINE ARGUMENTS
    ifile = "testdata/urv_email.txt"
    iterCount = 0
    iK1 = 0
    iK2 = 0
    iDebug = 0
    try:
        opts, args = getopt.getopt(sys.argv[1:],"hi:t:v:e:d")
    except getopt.GetoptError as err:
        print(err)
        print_usage()
        sys.exit(2)
    for opt, arg in opts:
        if opt == "-h":
            print_usage()
            sys.exit()
        elif opt == "-i":
            ifile = arg
        elif opt == "-t":
            iterCount = int(arg)
        elif opt == "-v":
            iK1 = int(arg)
        elif opt == "-e":
            iK2 = int(arg)
        elif opt == "-d":
            iDebug = 1
            

     
    # Parse payoff function parameter BEFORE config/pool creation
    # Check if payoff function is specified as last argument
    if len(sys.argv) >= 4:
        payoff_function_name = sys.argv[-1]
        try:
            payoff_function = get_payoff_function(payoff_function_name)
            print(f"Using payoff function: {payoff_function_name}")
            payoff_functions.fitness_count = 0
        except ValueError:
            payoff_function_name = 'pairwise'
            payoff_function = get_payoff_function(payoff_function_name)
            print(f"Using default payoff function: {payoff_function_name}")
            payoff_functions.fitness_count = 0
    else:
        payoff_function_name = 'pairwise'
        payoff_function = get_payoff_function(payoff_function_name)
        print(f"Using default payoff function: {payoff_function_name}")
        payoff_functions.fitness_count = 0
    
    mainConfig = config(ifile, iterCount, iK1, iK2, iDebug)
    print_config(mainConfig)
    
    minVal = math.inf
    minR = mainConfig.NIL
    minSS = []
    minEE = []


    method = CNEP1a_2_G1
    plotNo = 111
    minValE = [math.inf,[],[],[]]

    # EXECUTION - pass payoff_function NAME to workers via initializer
    que = Queue()
    pool = Pool(processes=mainConfig.pool_size, initializer=pool_init, initargs=(que, payoff_function_name))
    run(pool)
    pool.close()
    #pool.join()
    
    # SEARCHING FOR BEST SOLUTION
    que.put('STOP')
    for i in iter(que.get, 'STOP'):
        if (i[0]<minValE[0]):
            minValE = i

    # UNPACKING BEST SOLUTION
    [minVal,minSS,minEE] = minValE

    
    # PRINTING SOLUTION DETAILS
    minR = mainConfig.G.copy()
    minR.remove_nodes_from(minSS)
    minR.remove_edges_from(minEE)


    output_dir = Path("outputs/reruns/greedy")
    output_dir.mkdir(parents=True, exist_ok=True)
    output = output_dir / f"{sys.argv[2]}_{Path(sys.argv[1]).name}"
    f = open(output, "w+")

    print('Modified graph properties:\n-----------------')
    print("Edge count: " + str(len(minR.edges)))
    print("Node count: " + str(len(minR.nodes)),'\n')

    print('  Nodes removed: ',minSS, file=f)
    print('  Edges removed: ',minEE, file=f)
    print('MinVal achieved: ',minVal, file=f)

    f.close()
    # Original and modified graph details
    #print('Original nodes: ',sorted(G.nodes, key=lambda tup: tup[0]))
    #print('Original edges: ',sorted(G.edges, key=lambda tup: tup[0]))
    #print('Modified nodes: ',sorted(minR.nodes, key=lambda tup: tup[0]))
    #print('Modified edges: ',sorted(minR.edges, key=lambda tup: tup[0]))

    ## csak ha van grafikus felulet
    #plt.subplot(plotNo)
    #nx.draw(minR, with_labels=True) #, pos=nx.planar_layout(G), node_color='r', edge_color='b')
